name: cellpose-tfg
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8
  - pytorch=2.4.1
  - torchvision=0.20.0
  - torchaudio=2.4.1
  - cudatoolkit=12.4
  - numpy=1.24.4
  - scipy=1.10.1
  - scikit-image=0.21.0
  - scikit-learn=1.3.2
  - opencv-python-headless=4.10.0.84
  - matplotlib=3.7.2
  - pyqt=5.15.2
  - numba=0.58.1
  - llvmlite=0.41.1
  - tifffile=2023.7.10
  - fastremap=1.15.0
  - roifile=2023.5.12
  - pywavelets=1.4.1
  - pycocotools=2.0.7
  - pip
  - pip:
      - cellpose==3.1.0
      - albumentations==1.4.18
      - imagecodecs==2023.3.16
      - imageio==2.35.1
      - qtpy==2.4.1
      - pyqtgraph==0.13.3
      - tqdm==4.66.5
      - natsort==8.4.0
      - joblib==1.4.2
      - threadpoolctl==3.5.0
      - zipp==3.20.1
      - importlib-metadata==8.4.0
      - pycocoevalcap==1.2
      - fsspec==2024.6.1
      - google-cloud-storage==2.18.2
      - google-auth==2.34.0
      - google-api-core==2.19.2
      - protobuf==5.28.0
      - pydantic==2.9.2
      - typing-extensions==4.12.2
      - albucore==0.0.17
      - lazy-loader==0.4
      - eval-type-backport==0.2.0
      - annotated-types==0.7.0